### ISSUE TITLE
Use ESM instead of CommonJS

### ISSUE THREAD

**Issue by lydell** [supermario/elm-pkg-js#12]
Instead of:

```js
exports.init = async function init(app) {
    // package javascript goes here
}
```

Use:

```js
export async function init(app) {
    // package javascript goes here
}
```

CommonJS (or the version of it that Node.js supports) is an old module system. These day we have standard ECMAScript modules (ESM), which are well supported by browsers, Node.js and build tools.

I think it would make more sense to use ESM in elm-pkg-js.

**Comment by supermario** [comment]
Thanks for the tip @lydell !
